// VENDORIZADO desde harness-daemon/contract/harness.gen.ts (ADR-0003).
// NO editar a mano. Resync: scripts/sync-contract.sh. Fuente de verdad:
// los structs Go de internal/api del daemon.
// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/api. DO NOT EDIT.
// Fuente de verdad: los structs Go del daemon. Regenerar: `go generate ./...`.
// Contrato daemon→UI — ver ADR-0003 (workspace corvux).

//////////
// source: drafts.go

export interface DraftDoc {
  path: string; // relativo al workspace
  kind: string; // abogado | constitution | spec | map
  title: string; // legible
}
/**
 * LawDoc — un documento de la ley con su estado, ratificado o no: el visor
 * no desaparece al firmar ("no quites que pueda ver los docs").
 */
export interface LawDoc {
  path: string;
  kind: string;
  title: string;
  status: string; // draft | ratified | plain (sin frontmatter de status)
  agent: string | null; // cluster re-excavable (svc-*)
}

//////////
// source: inventory.go
/*
inventory.go — lo que el daemon lee de los ARCHIVOS del workspace para las
vistas Docs y Skills & MCP, y la metadata de git por tarea. Es el port fiel
del panel de Python (scan_toolbox / mcp_servers / task_git / task_events):
nada de prosa inventada; si un archivo no está, no aparece.
*/

export interface CmdDoc {
  name: string;
  desc: string;
  args: string;
}
export interface AgentDoc {
  name: string;
  desc: string;
}
export interface MakeDoc {
  target: string;
  desc: string;
}
export interface SkillDoc {
  name: string;
  desc: string;
  ok: boolean;
}
export interface Toolbox {
  version: string;
  commands: CmdDoc[];
  agents: AgentDoc[];
  make: MakeDoc[];
  gates: string[];
  hooks: string[];
  skills: SkillDoc[];
}
export interface McpServer {
  name: string;
  command: string;
  args: string[];
  wrapped: boolean;
  bin_ok: boolean;
  secrets_ok: boolean | null;
  env: string[];
  probe: McpProbe | null; // la sonda viva (OPERAR): se llena al "Probar"
}
/**
 * McpProbe: resultado del handshake JSON-RPC real contra un servidor MCP.
 * "funciona" = arrancó y contestó initialize; tools = lo que expone de verdad.
 */
export interface McpProbe {
  ok: boolean;
  ms: number /* int64 */;
  server: string | null;
  version: string | null;
  error: string | null;
  auth_hint: boolean | null;
  at: string | null;
  tools: string[] | null;
}
/**
 * ── git por tarea (port de task_git) ────────────────────────────────────
 */
export interface RepoGit {
  repo: string;
  branch: string;
  ahead: number /* int */;
  dirty: boolean;
  last_subject: string;
  last_ts: number /* int64 */;
  pr: {
    number: number /* int */;
    state: string;
    url: string;
  } | null;
  pushed_direct: boolean;
}
export interface TaskGit {
  repos: RepoGit[];
  read: string[];
}

//////////
// source: mcp_probe.go

export interface McpConf {
  Command: string;
  Args: string[];
  Env: { [key: string]: string};
}

//////////
// source: op.go
/*
op.go — el plano de OPERAR del daemon (ADR-0010: crear trabajo, jamás
merges). Port del panel de Python, con los mismos guardrails:

  - Token anti-CSRF por arranque, inyectado en el HTML servido y exigido en
    el header X-Corvux-Token de todo POST (un <form> ajeno no puede poner
    headers custom sin un preflight CORS que este server jamás contesta).
  - Check de Host contra DNS rebinding. Solo 127.0.0.1 (el listener ya).
  - Secretos write-only: se validan contra el proveedor ANTES de guardarse
    (0600), jamás se devuelven, jamás se loguean, jamás pasan por un agente.
  - Todo lo lanzado pasa por LOS MISMOS gates: a main solo se llega por
    ship.sh. Aquí no hay botón de merge.
*/

/**
 * Op es el plano de operar de UN workspace.
 */
export interface Op {
  Token: string; // por arranque; viaja en el HTML, vuelve en el header
  WS: string; // ruta del workspace
  WSID: string;
  DB: any /* store.Queryer */; // almacén dialecto-agnóstico (SQLite o Postgres)
  Port: number /* int */;
}

//////////
// source: session.go
/*
session.go — el drill-down de razonamiento por agente (/api/session), armado
del store: agentes con su usage/costo + el hilo (texto/pensamiento/tool) que
el colector persiste ya redactado. Es la última pieza de paridad de lectura.
*/

export interface ThreadItem {
  k: string; // text | think | tool
  ts: number /* int64 */;
  t: string;
  inp: string | null;
}
export interface AgentDetail {
  id: string;
  who: string;
  type: string;
  model: string;
  active: boolean;
  depth: number /* int */;
  first_ts: number /* int64 */;
  last_ts: number /* int64 */;
  elapsed: number /* int64 */;
  usage: Usage;
  cost: number /* float64 */ | null;
  thread: ThreadItem[];
}
export interface SessionDetail {
  id: string;
  short: string;
  agents: AgentDetail[];
}

//////////
// source: snapshot.go
/*
Package api construye el snapshot que consume el frontend React — el MISMO
contrato que sirve el panel de Python, pero leído del SQLite del daemon en
vez de los archivos. Es la Fase 1: el daemon se vuelve el backend de lectura.

Honesto sobre lo que HOY degrada (se suma en fases siguientes): el daemon es
solo-lectura (op:false, Operar oculto); no trae aún el texto en vivo por
agente, el hilo de razonamiento, ni los chips de git — el frontend cae con
gracia a sus vacíos cuando esos campos faltan.
*/

export interface Usage {
  in: number /* int64 */;
  out: number /* int64 */;
  cache_read: number /* int64 */;
  cache_creation: number /* int64 */;
}
export interface Agent {
  id: string;
  type: string;
  desc: string;
  model: string;
  active: boolean;
  first_ts: number /* int64 */;
  last_ts: number /* int64 */;
  idle: number /* int64 */;
  elapsed: number /* int64 */;
  usage: Usage;
  cost: number /* float64 */ | null;
  depth: number /* int */;
}
export interface Session {
  id: string;
  short: string;
  model: string;
  n_agents: number /* int */;
  n_active: number /* int */;
  peak: number /* int */;
  idle: number /* int64 */;
  tokens: Tokens;
  cost: number /* float64 */ | null;
  agents: Agent[];
  /**
   * LiveBy dice CÓMO sabemos que está viva: "herdr" = una terminal de herdr la
   * corre AHORA (verdad de campo); "recent" = el transcript se tocó hace poco
   * pero herdr no lo confirma (terminó hace nada o corre fuera de herdr);
   * "" = en reposo. Lo llena EnrichLiveness. El mtime ya no miente "trabajando".
   */
  live_by: string;
  /**
   * cwd de la sesión: ancla su tarea (worktrees/<id>/) y se cruza con pane.cwd
   * de herdr. Ahora expuesto para agrupar sesiones dentro de su tarea.
   */
  cwd: string | null;
}
export interface Tokens {
  out: number /* int64 */;
  cache_read: number /* int64 */;
}
export interface Event {
  ts: string;
  kind: string;
  task: string;
  actor: string;
  summary: string;
  ok: boolean | null;
}
export interface Task {
  id: string;
  title: string;
  origin: string;
  phase: string;
  done: string[];
  verdicts: Verdicts;
  assumptions: string[];
}
export interface Verdicts {
  pass: number /* int */;
  total: number /* int */;
}
export interface DayCost {
  day: string;
  cost: number /* float64 */;
  out: number /* int64 */;
  unpriced: boolean;
  by_model: { [key: string]: number /* float64 */};
}
export interface ModelCost {
  model: string;
  in: number /* int64 */;
  out: number /* int64 */;
  cache_read: number /* int64 */;
  cache_creation: number /* int64 */;
  cost: number /* float64 */ | null;
}
export interface Price {
  Input: number /* float64 */;
  Output: number /* float64 */;
  CRead: number /* float64 */;
  CW5m: number /* float64 */;
  CW1h: number /* float64 */;
}
/**
 * Snapshot es el objeto que /api/state y /api/stream devuelven.
 */
export interface Snapshot {
  ts: number /* int64 */;
  sessions: Session[];
  events: Event[];
  tasks: Task[];
  tokens: Tokens;
  cost: number /* float64 */ | null;
  days: DayCost[];
  models: ModelCost[];
  prices: { [key: string]: PubP};
  unpriced: string[];
  connections: { [key: string]: boolean};
  runs: { [key: string]: any}[];
  mode: string;
  op: boolean;
  workspace: WsInfo;
  toolbox: Toolbox | null;
  mcp: McpServer[];
  herdr: any | null;
  targets: Target[]; // máquinas remotas (VPS) por SSH
  archived_tasks: string[]; // tareas ocultas (el bus las revive si no se excluyen)
  warning: string | null;
  /**
   * Init es el estado del wizard de onboarding (initflow.PublicState) cuando
   * hay un init activo; `any` para no crear ciclo de imports con initflow.
   */
  init: any | null;
  /**
   * Drafts: la ley propuesta y sin firmar (constituciones, specs, map) —
   * se ratifica desde el panel (OpRatify). Law: TODA la ley con estado
   * (el visor permanece tras firmar; re-excavable por cluster).
   */
  drafts: DraftDoc[] | null;
  law: LawDoc[] | null;
}
export interface WsInfo {
  name: string;
  path: string;
}
export interface PubP {
  input: number /* float64 */;
  output: number /* float64 */;
}

//////////
// source: targets.go

/**
 * Target es una máquina remota (VPS) donde corre herdr, alcanzable por SSH. El
 * panel local la controla vía `ssh <SSH> herdr …`. SSH es un alias de
 * ~/.ssh/config o user@host — la AUTENTICACIÓN la maneja OpenSSH (llaves), el
 * daemon nunca toca credenciales. El frontend manda el NAME; el daemon lo
 * resuelve al SSH validado — así el navegador nunca inyecta un target de exec.
 */
export interface Target {
  name: string;
  ssh: string;
  /**
   * Path del workspace del harness EN el VPS (para `harnessd snapshot
   * --workspace <path>`). El workspaceID es el mismo en ambas máquinas (se
   * deriva del git remote), sólo cambia la ruta. Opcional.
   */
  path: string | null;
}
